name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Hunter
        uses: actions/cache@v3
        with:
          path: ~/.hunter
          key: ${{ runner.os }}-hunter-${{ hashFiles('cmake/HunterGate.cmake') }}

      - name: Install dependencies (CMake)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure & Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j
